'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property button_selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_unselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_unselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kick_01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_01", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_02", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_03() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_03", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_04() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_04", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_05() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_05", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_06() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_06", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_07() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_07", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_08() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_08", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_09() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_09", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property kick_10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("kick_10", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
